defmodule Reqs do

  def start(leader, mode) do
    reqs = get100(mode)
           |> Enum.with_index(1)
    Graft.Timer.timestamp(:start)
    for i1 <- 0..9 do
      for {req, i2} <- reqs do
        Graft.Timer.timestamp({:start, i1*100+i2})
        ans = Graft.request(leader, req)
        IO.puts("Ans for #{i1*100+i2}: #{inspect ans}")
        Graft.Timer.timestamp({:end, i1*100+i2})
      end
    end
    Graft.Timer.timestamp(:end)
  end



  def get100(:n) do
    [
      {:add, 6},
      {:sub, 85},
      {:add, 1523},
      {:mul, 5},
      {:sub, 4},
      {:add, 596},
      {:sub, 54},
      {:add, 93},
      {:add, 2},
      {:sub, 16},
      {:add, 325},
      {:mul, 4},
      {:add, 12},
      {:add, 247},
      {:sub, 264},
      {:add, 54},
      {:mul, 5},
      {:sub, 64},
      {:add, 971},
      {:sub, 45},
      {:add, 568},
      {:mul, 1},
      {:add, 24},
      {:add, 6},
      {:sub, 85},
      {:add, 23},
      {:mul, 5},
      {:sub, 4},
      {:add, 596},
      {:sub, 54},
      {:add, 93},
      {:add, 2},
      {:sub, 16},
      {:add, 325},
      {:sub, 54},
      {:add, 123},
      {:mul, 5},
      {:mul, 6},
      {:add, 284},
      {:sub, 53},
      {:add, 37},
      {:mul, 4},
      {:sub, 29},
      {:mul, 4},
      {:sub, 24},
      {:add, 6},
      {:sub, 85},
      {:add, 23},
      {:mul, 5},
      {:add, 4},
      {:add, 596},
      {:sub, 54},
      {:add, 93},
      {:add, 2},
      {:sub, 16},
      {:add, 1},
      {:mul, 4},
      {:add, 80},
      {:add, 23},
      {:sub, 54},
      {:add, 66},
      {:mul, 4},
      {:sub, 43},
      {:add, 5},
      {:sub, 84},
      {:add, 5},
      {:mul, 8},
      {:sub, 62},
      {:add, 35},
      {:sub, 85},
      {:add, 548},
      {:mul, 5},
      {:sub, 12},
      {:add, 247},
      {:sub, 264},
      {:add, 54},
      {:mul, 8},
      {:sub, 64},
      {:add, 971},
      {:sub, 45},
      {:add, 568},
      {:mul, 1},
      {:sub, 63},
      {:add, 325},
      {:sub, 54},
      {:add, 123},
      {:mul, 6},
      {:sub, 96},
      {:add, 284},
      {:sub, 53},
      {:add, 37},
      {:mul, 4},
      {:sub, 29},
      {:sub, 264},
      {:add, 54},
      {:mul, 5},
      {:sub, 64},
      {:add, 971},
      {:sub, 45},
      {:mul, 4}
    ]
  end

  def get100(:f) do
    [
      {:add, 6},
      {:sub, 85},
      {:add, 1523},
      {:mul, 5},
      {:sub, 4},
      {:add, 596},
      {:sub, 54},
      {:add, 93},
      {:add, 2},
      {:div, 0},
      {:add, 325},
      {:mul, 4},
      {:add, 12},
      {:add, 247},
      {:sub, 264},
      {:add, 54},
      {:mul, 8},
      {:sub, 64},
      {:add, 971},
      {:div, 0},
      {:add, 568},
      {:mul, 1},
      {:add, 24},
      {:add, 6},
      {:sub, 85},
      {:add, 23},
      {:mul, 5},
      {:sub, 4},
      {:add, 596},
      {:div, 0},
      {:add, 93},
      {:add, 2},
      {:sub, 16},
      {:add, 325},
      {:sub, 54},
      {:add, 123},
      {:mul, 6},
      {:mul, 6},
      {:add, 284},
      #{:div, 0},
      {:add, 37},
      {:mul, 1},
      {:sub, 29},
      {:mul, 4},
      {:sub, 24},
      {:add, 6},
      {:sub, 85},
      {:add, 23},
      {:mul, 6},
      {:div, 0},
      {:add, 596},
      {:sub, 54},
      {:add, 93},
      {:add, 2},
      {:sub, 16},
      {:add, 1},
      {:mul, 5},
      {:add, 80},
      {:add, 23},
      {:div, 0},
      {:add, 66},
      {:mul, 2},
      {:sub, 43},
      {:add, 5},
      {:sub, 84},
      {:add, 5},
      {:mul, 6},
      {:sub, 62},
      {:add, 35},
      {:div, 0},
      {:add, 548},
      {:mul, 4},
      {:sub, 12},
      {:add, 247},
      {:sub, 264},
      {:add, 54},
      {:mul, 8},
      {:sub, 64},
      {:add, 971},
      {:div, 0},
      {:add, 568},
      {:mul, 1},
      {:sub, 63},
      {:add, 325},
      {:sub, 54},
      {:add, 123},
      {:mul, 6},
      {:sub, 96},
      {:add, 284},
      {:div, 0},
      {:add, 37},
      {:mul, 4},
      {:sub, 29},
      {:sub, 264},
      {:add, 54},
      {:mul, 5},
      {:sub, 64},
      {:add, 971},
      {:sub, 45},
      {:div, 0}
    ]
  end

end
